### ISSUE TITLE
Error when creating a single key wallet from cold card

### ISSUE THREAD

**Issue by ralake** [cryptoadvance/specter-desktop#645]
This error happens when i create a single key wallet from a coldcard with wallets exported from the card by micro SD

<img width="812" alt="Screenshot 2020-11-20 at 11 32 57" src="https://user-images.githubusercontent.com/8901119/99797272-dce9e600-2b26-11eb-9b87-eff9a03e0d86.png">

**Comment by ben-kaufman** [comment]
Hi, which export format did you select on the coldcard?

**Comment by ralake** [comment]
> Hi, which export format did you select on the coldcard?

Should have been the generic json

**Comment by ben-kaufman** [comment]
Where did you try to import it? In the add device page or add wallet page? If the latter then you should import it in the device page, and only after adding the device create a wallet which uses that device.

**Comment by ralake** [comment]
> Where did you try to import it? In the add device page or add wallet page? If the latter then you should import it in the device page, and only after adding the device create a wallet which uses that device.

Im pretty sure that is the process I followed, but I will "forget" the device to get a clean state and try again to make sure 👍

**Comment by ben-kaufman** [comment]
Ok please let me know if that still happens. Also would be useful to know the Specter version you're running, the OS, and at which step exactly in the process did it occur.

**Comment by ralake** [comment]
> Ok please let me know if that still happens. Also would be useful to know the Specter version you're running, the OS, and at which step exactly in the process did it occur.

Sure - Ill try the process again tonight and update this issue with what I find

**Comment by ralake** [comment]
I have just done the exact process you describe and the error still occurs...

Specter version 0.9.2
Mac OS Mojave v10.14.16

The error happens when I click "Create wallet"

**Comment by ralake** [comment]
I get a similar error at the same point if i forget the device and try to create the wallet without creating the device to start with

<img width="808" alt="Screenshot 2020-11-20 at 14 01 06" src="https://user-images.githubusercontent.com/8901119/99808615-090e6280-2b39-11eb-96f5-a88af7ab2169.png">

**Comment by stepansnigirev** [comment]
Can you try with 0.10.0 we just released?

**Comment by ralake** [comment]
> Can you try with 0.10.0 we just released?

Sure

**Comment by ralake** [comment]
@stepansnigirev unfortunately still happening...

<img width="821" alt="Screenshot 2020-11-22 at 15 52 56" src="https://user-images.githubusercontent.com/8901119/99908488-ddc37900-2cda-11eb-8193-1e18d280d85d.png">

**Comment by eriknylund** [comment]
I'm seeing two similar errors on _specterd-v0.10.1-x86_64-linux-gnu_ depending on which path I take:

Both approaches begin with clicking **Add new wallet** in the left sidebar:

![image](https://user-images.githubusercontent.com/20860124/100261828-ff7b6500-2f53-11eb-849f-b35645a010a0.png)

### First approach

1. Single key wallet
2. Add new device
3. ColdCard
4. Add name
5. Upload from SD Card, select coldcard-export.json
6. Add device 

This returns Server error! Exception: Invalid literal for int() with base 10: "

![image](https://user-images.githubusercontent.com/20860124/100261988-36517b00-2f54-11eb-9d9b-19d6f7e793b2.png)

### Second approach

1. Import from wallet software
![image](https://user-images.githubusercontent.com/20860124/100261956-29cd2280-2f54-11eb-9602-6dcedc86de2b.png)

2. Choose files, select coldcard-export.json or any other format that the ColdCard exports
3. Continue

This returns Server error! Exception 'blockheight'

![image](https://user-images.githubusercontent.com/20860124/100261976-32255d80-2f54-11eb-8183-232cb0abe1d5.png)

**Comment by ralake** [comment]
Any idea on what could be causing this? Quite a big feature that doesnt seem to work...

**Comment by stepansnigirev** [comment]
> Upload from SD Card, select coldcard-export.json

How did you generate the files on the coldcard that you are trying to import?

**Comment by ben-kaufman** [comment]
You should add the coldcard file as a device, clicking add device then choosing coldcard and uploading the file. Then you should create a wallet on Specter (not import).

The flow on Specter is add a device (with the coldcard file for example), then create a wallet on Specter selecting that device.
The import wallet button is a different thing, for importing a wallet from a software like another Specter, or Sparrow or FullyNoded

**Comment by eriknylund** [comment]
> You should add the coldcard file as a device, clicking add device then choosing coldcard and uploading the file. Then you should create a wallet on Specter (not import).
> 
> The flow on Specter is add a device (with the coldcard file for example), then create a wallet on Specter selecting that device.
> The import wallet button is a different thing, for importing a wallet from a software like another Specter, or Sparrow or FullyNoded

Thanks for clarifying. Would it be possible to give a more user friendly error message if you try to import something that is not supported here?

**Comment by eriknylund** [comment]
> > Upload from SD Card, select coldcard-export.json
> 
> How did you generate the files on the coldcard that you are trying to import?

I went into the Advanced -> MicroSD Card -> Export Wallet -> menu and then I exported all options there are:

1. Bitcoin Core
2. Electrum Wallet
3. Wasabi Wallet
4. Generic JSON

I tested all four on specterd-v0.10.1-x86_64-linux-gnu and I can't get anyone of the files imported. I'll try an older version later today to see if it's related to specter or if it's a case of PEBKAC.

**Comment by eriknylund** [comment]
I downloaded specterd-v0.9.2-x86_64-linux-gnu.zip and performed the same steps. Using the file coldcard-export.json I can import the wallet without problems. Repeated the same steps on specterd-v0.10.1-x86_64-linux-gnu.zip once more and it fails with the Invalid literal for int() with base 10 exception as before. I'll try v0.10.0 next to see how that version behaves. 

Once successfully imported with v0.9.2 I see it in v0.10.1 so that will allow me to continue using v0.10.1 from that point on.

**Comment by ralake** [comment]
> You should add the coldcard file as a device, clicking add device then choosing coldcard and uploading the file. Then you should create a wallet on Specter (not import).
> 
> The flow on Specter is add a device (with the coldcard file for example), then create a wallet on Specter selecting that device.
> The import wallet button is a different thing, for importing a wallet from a software like another Specter, or Sparrow or FullyNoded

Followed this exactly a number of times, no luck, same error.

**Comment by ralake** [comment]
Also tried creating a wallet on v0.9.2 and get the same problem I have in the screenshots I posted above....

**Comment by eriknylund** [comment]
> Also tried creating a wallet on v0.9.2 and get the same problem I have in the screenshots I posted above....

That's an interesting find! I'm on macOS Catalina 10.15.7 so I could see how that behaves with these three versions.

**Comment by ralake** [comment]
@eriknylund we seem to be getting different error messages when wallet creation fails though. You have `invalid literal for int()` and I have `TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by ben-kaufman** [comment]
Hi, so this is the exact flow for how to add a Coldcard wallet to Specter (air-gapped using the SD card). 
I divided it into 10 steps with screenshots to make it clearer. Are these the actions you are taking? If yes at which one of them do you get an error?

1. Click "Add new device" button on the left sidebar
<img width="1787" alt="Screen Shot 2020-12-01 at 12 09 05" src="https://user-images.githubusercontent.com/10667901/100726811-1a276100-33ce-11eb-9c59-90ba67438152.png">

2. Select Coldcard as the device type
<img width="1792" alt="Screen Shot 2020-12-01 at 11 53 29" src="https://user-images.githubusercontent.com/10667901/100726401-953c4780-33cd-11eb-978a-3a687d1b2fd5.png">

3. Click upload from SD Card
<img width="1792" alt="Screen Shot 2020-12-01 at 11 53 37" src="https://user-images.githubusercontent.com/10667901/100726462-a4bb9080-33cd-11eb-92f7-3056acfb0655.png">

4. Select the file you exported from the Coldcard to the SD card SD Card (to export, go to your Coldccard and then select Advanced -> MicroSD Card -> Export Wallet -> Generic JSON. When asked for account, select acount number (default is 0) and confirm the export.)
<img width="1792" alt="Screen Shot 2020-12-01 at 12 26 59" src="https://user-images.githubusercontent.com/10667901/100729099-05989800-33d1-11eb-8d81-277234503636.png">

5. You should see some xpubs populated in the table.
Name the device (i.e. "My Coldcard" or whatever you would like to name it) and click "Add device" at the bottom.
<img width="1792" alt="Screen Shot 2020-12-01 at 12 27 36" src="https://user-images.githubusercontent.com/10667901/100728833-b6526780-33d0-11eb-8279-2d3c9852d471.png">

6. You should see "New Device Was Added Successfully popup.
Now either click on the "Add new wallet" button on the left sidebar, or on the "Create wallet" in the popup (if you click on this, skip to step 9 here, Specter will automatically do steps 7 + 8).
<img width="1792" alt="Screen Shot 2020-12-01 at 12 31 06" src="https://user-images.githubusercontent.com/10667901/100729182-1fd27600-33d1-11eb-8324-3b688c7d962a.png">

7. After clicking on the "Add new wallet" button on the left sidebar, click Single Key Wallet
<img width="1792" alt="Screen Shot 2020-12-01 at 12 10 32" src="https://user-images.githubusercontent.com/10667901/100727075-712d3600-33ce-11eb-83de-bdd783febd1d.png">

8. Click on the Coldcard device you just added (you'll identify it by the name you gave it on step 5).
<img width="1792" alt="Screen Shot 2020-12-01 at 12 10 37" src="https://user-images.githubusercontent.com/10667901/100727133-84400600-33ce-11eb-897c-fa77b64a18b8.png">

9. Name the wallet, choose whatever address type should be Nested Segwit or Segwit, select if you would like to rescan for existing funds, and then click "Create wallet" at the bottom.
(You can also select between the keys you added using the table of keys, but it is recommended to go with the default key)
<img width="1792" alt="Screen Shot 2020-12-01 at 12 10 52" src="https://user-images.githubusercontent.com/10667901/100727184-91f58b80-33ce-11eb-96b3-907c1d8b2e39.png">

10. You should see a Pacman loading screen, followed by this popup of New wallet was created successfully!".
<img width="1792" alt="Screen Shot 2020-12-01 at 12 11 00" src="https://user-images.githubusercontent.com/10667901/100727217-9d48b700-33ce-11eb-8413-42b343ff3dd2.png">

**Comment by eriknylund** [comment]
@ben-kaufman Thanks for walking me through the steps! For me, it fails on step 5, **no xpubs are ever populated**. When I then click "Add device" to proceed to step 6 I get the error message.

As I now re-tested this I noticed the **Manual configuration** option at the bottom (visible on the picture for step 2). On that page, I add a name, select ColdCard from the dropdown, click Choose files and select coldcard-export.json, then click the Continue button. With this approach the wallet is successfully imported.

**Comment by ben-kaufman** [comment]
@eriknylund ok great, so you should with the "manual" option, after adding the device successfully, be able to continue from step 6, does that work for you?

As for the issue with step 5, the file you're trying with it the Generic type from Coldcard right?
It is strange, because both use the same logic to extract the xpubs from the file as far as I can remember, I'll check...

**Comment by ralake** [comment]
@ben-kaufman I get to step nine, click `Create wallet` and it shows the modal with the error message I have in screenshots in previous posts - error is `TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by eriknylund** [comment]
> @eriknylund ok great, so you should with the "manual" option, after adding the device successfully, be able to continue from step 6, does that work for you?
> 
> As for the issue with step 5, the file you're trying with it the Generic type from Coldcard right?
> It is strange, because both use the same logic to extract the xpubs from the file as far as I can remember, I'll check...

I'm not sure I follow you. How would I be able to continue from step 6 when the wallet is already imported?

I can recreate the error by adding a name (which is required by the UI), but then skipping the upload step, as soon as I click the "Add Device" button it fails. It seems to me either the uploading of the file or the parsing of it does not work as intended. I don't see anything happening in the network inspector that would indicate the file is being sent to specterd. 

As the exported JSON file works in manual mode, I'm assuming it is exported in the right format, unless you support many of the formats that can be exported from the ColdCard and only some work in the default (non-manual) mode.

**Comment by ben-kaufman** [comment]
Thanks @ralake , I see then that it fails with
https://github.com/cryptoadvance/specter-desktop/blob/4fd68f88313abc2a4bb5dbacb966bef5fd20cf23/src/cryptoadvance/specter/wallet_manager.py#L190

I understand that you are using macOS Mojave right? I think the desktop app should work with it, but now I think it might now be fully compatible then... Can you please try installing and running Specter from pip instead and let me know if that gives the same error?

**Comment by ralake** [comment]
> https://github.com/cryptoadvance/specter-desktop#installing-specter-from-pip

will do

**Comment by ben-kaufman** [comment]
@eriknylund the manual way should create for you the device (so you should be able to see it on the left sidebar under the device list), but not the wallet, (the wallets list in the left sidebar should be empty). You can as in step #6 click on "Add new wallet" on the left sidebar to use the device to add a new wallet.
I need to check if both manual and the newer add device flows support the same formats...

**Comment by eriknylund** [comment]
> @eriknylund the manual way should create for you the device (so you should be able to see it on the left sidebar under the device list), but not the wallet, (the wallets list in the left sidebar should be empty). You can as in step #6 click on "Add new wallet" on the left sidebar to use the device to add a new wallet.
> I need to check if both manual and the newer add device flows support the same formats...

Thanks for clarifying, I am back on track :) Yes I was able to continue and create the wallet using the left sidebar as described in step 6 and get all the way to step 10.

**Comment by ralake** [comment]
@ben-kaufman i get an error `ERROR: Could not find a version that satisfies the requirement hwi==1.1.2` when running `pip3 install cryptoadvance.specter` - even though in `requirements.txt` the version required is `1.2.0` - https://github.com/cryptoadvance/specter-desktop/blob/master/requirements.txt#L125 - any reason why that is happening?

**Comment by stepansnigirev** [comment]
Do you use python3.9? HWI is available only in `>=3.6` and  `<3.9` at the moment...
Maybe you can try with python3.8.

**Comment by ralake** [comment]
ah yeah i have 3.9, ill try 3.8 👍

**Comment by ralake** [comment]
> Thanks @ralake , I see then that it fails with
> https://github.com/cryptoadvance/specter-desktop/blob/4fd68f88313abc2a4bb5dbacb966bef5fd20cf23/src/cryptoadvance/specter/wallet_manager.py#L190
> 
> I understand that you are using macOS Mojave right? I think the desktop app should work with it, but now I think it might now be fully compatible then... Can you please try installing and running Specter from pip instead and let me know if that gives the same error?
> https://github.com/cryptoadvance/specter-desktop#installing-specter-from-pip

Same error unfortunately... It did lead me to see my python setup was rather wonky so thats now better than it was...

**Comment by ralake** [comment]
I did some digging and `self.working_folder` is `None`

**Comment by ralake** [comment]
If i print `self.working_folder` on line 64 in `wallet_manager` i can see it get set to a sensible value. Multiple `WalletManager` seem to be being instantiated (is that ok?) during the initialisation of the app (I open specter, then open bitcoin core) - only one of these sets a string value to `self.working_folder`. When I create a wallet, `self.working_folder` is `None`

**Comment by ralake** [comment]
Also interesting. If i start bitcoin core first and let is sync, then open specter, it never moves off the loading screen. If i start specter first, let it load up, then start bitcoin core, it seems to work (other than the bug reported in this issue)

**Comment by ben-kaufman** [comment]
Thanks for the info! That's very strange, I'll try to dig into that...

**Comment by ralake** [comment]
This is no longer an issue for me. It seems to be an issue with my original setup (Bitcoin Core full node with data directory on external SSD). I have since set up a pruned node on my laptop and downloaded the most recent version of Specter and I can successfully create a wallet. Not sure why the external SSD would make a difference but it clearly does...
